# inspired by https://github.com/rectorphp/rector/blob/master/.travis.yml
language: php

dist: bionic

php: 7.4

jobs:
    include:
        -
            name: "Split Monorepo"
            if: (branch = master OR tag IS present) && type = push
            script:
                - composer update --ansi
                # travis_retry to prevent fails
                - travis_retry packages/monorepo-builder/bin/monorepo-builder split --max-processes 6 --ansi

        -
            name: Compile and Release ecs.phar
            if: (branch = master OR tag IS present) && type = push
            script:
                - cd packages/easy-coding-standard/compiler

                # see https://gist.github.com/jeffersonmartin/d0d4a8dfec90d224d14f250b36c74d2f
                # see https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens
                - composer config -g github-oauth.github.com $GITHUB_TOKEN --ansi

                - composer install --ansi
                - travis_retry bin/compile --ansi
                - ../tmp/ecs.phar --debug --ansi

                - cd ..

                # reuse tmp/ecs.phar from previous job
                - git clone https://${GITHUB_TOKEN}@github.com/symplify/easy-coding-standard-prefixed.git easy-coding-standard-prefixed > /dev/null 2>&1
                - cp tmp/ecs.phar easy-coding-standard-prefixed/ecs.phar
                - cp tmp/ecs.phar easy-coding-standard-prefixed/ecs
                - cd easy-coding-standard-prefixed
                - git config user.name "TomasVotruba"
                - git config user.email "tomas.vot@gmail.com"
                - git add ecs ecs.phar

                - if [ "${TRAVIS_TAG}" != "" ]; then COMMIT_MSG="ECS ${TRAVIS_TAG}"; else COMMIT_MSG="Updated ECS to commit ${TRAVIS_COMMIT}"; fi

                - git commit -m "${COMMIT_MSG}"
                - travis_retry git push --quiet origin master --force

                - if [ "${TRAVIS_TAG}" != "" ]; then git tag "${TRAVIS_TAG}" && git push --quiet origin ${TRAVIS_TAG}; fi

        -
            name: Compile and Release monorepo-builder.phar
            if: (branch = master OR tag IS present) && type = push
            script:
                - cd packages/monorepo-builder/compiler

                # see https://gist.github.com/jeffersonmartin/d0d4a8dfec90d224d14f250b36c74d2f
                # see https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens
                - composer config -g github-oauth.github.com $GITHUB_TOKEN --ansi

                - composer install --ansi
                - travis_retry bin/compile --ansi
                - ../tmp/monorepo-builder.phar --ansi

                - cd ..

                # reuse tmp/monorepo-builder.phar from previous job
                - git clone https://${GITHUB_TOKEN}@github.com/symplify/monorepo-builder-prefixed.git monorepo-builder-prefixed > /dev/null 2>&1
                - cp tmp/monorepo-builder.phar monorepo-builder-prefixed/monorepo-builder.phar
                - cp tmp/monorepo-builder.phar monorepo-builder-prefixed/monorepo-builder
                - cd monorepo-builder-prefixed
                - git config user.name "TomasVotruba"
                - git config user.email "tomas.vot@gmail.com"
                - git add monorepo-builder monorepo-builder.phar

                - if [ "${TRAVIS_TAG}" != "" ]; then COMMIT_MSG="Monorepo Builder ${TRAVIS_TAG}"; else COMMIT_MSG="Updated Monorepo Builder to commit ${TRAVIS_COMMIT}"; fi

                - git commit -m "${COMMIT_MSG}"
                - travis_retry git push --quiet origin master --force

                - if [ "${TRAVIS_TAG}" != "" ]; then git tag "${TRAVIS_TAG}" && git push --quiet origin ${TRAVIS_TAG}; fi

notifications:
    email: false
