language: php

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
    depth: false

matrix:
    include:
        - php: 7.1
          env: COVERAGE="--coverage-clover coverage.xml"
        - php: 7.1
          env: CODE_ANALYSIS=true STANDALONE=true
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: MONOREPO_SPLIT=true
        - php: 7.3
          env: COMPOSER_FLAGS="--ignore-platform-reqs"

install:
    - composer update $COMPOSER_FLAGS

before_script:
    # make the script fail for any failed multi-line command (starts with "|" then new line)
    - set -e

    # disable xdebug if not coverage
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi

script:
    - vendor/bin/phpunit
    # disable xdebug

    - |
      if [[ $CODE_ANALYSIS == true ]]; then
          packages/EasyCodingStandard/bin/ecs check packages
          vendor/bin/phpstan analyse packages
      fi

    # each package standalone run https://stackoverflow.com/a/6787956/1348344
    - |
      if [[ $STANDALONE == true ]]; then
          for DIRECTORY in `find packages -mindepth 1 -maxdepth 1 -type d`
          do
              CMD="vendor/bin/phpunit $DIRECTORY"
              echo "Running '$CMD'"
              $CMD
          done

          # test run bin files
          packages/EasyCodingStandard/bin/ecs
          # test "check" options
          packages/EasyCodingStandard/bin/ecs check packages/ChangelogLinker/src --no-progress-bar --no-error-table --clear-cache
          packages/ChangelogLinker/bin/changelog-linker
          packages/Statie/bin/statie
          packages/LatteToTwigConverter/bin/latte-to-twig-converter
          packages/MonorepoBuilder/bin/monorepo-builder
      fi

    # validate monorepo <=> packages composer dependencies
    - packages/MonorepoBuilder/bin/monorepo-builder validate

after_script:
    # code coverage run + upload to coveralls.io
    - |
      if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" && $COVERAGE == true ]]; then
          vendor/bin/phpunit --coverage-clover coverage.xml
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
          php php-coveralls.phar --verbose
      fi

    - |
      if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" && $MONOREPO_SPLIT == true ]]; then
          # split monorepo to packages - only on merge to master
          # see https://www.tomasvotruba.cz/blog/2018/07/19/how-to-make-github-and-travis-split-monorepo-to-multiple-git-repositories-for-you/
          packages/MonorepoBuilder/bin/monorepo-builder split -v

          # run slow api test only on master, because they require token
          vendor/bin/phpunit --group api
      fi

notifications:
    email: false
