build: false

platform: x64

clone_folder: c:\package # directory the project is cloned into, is set into %APPVEYOR_BUILD_FOLDER% variable

cache:
  # cache composer
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%

install:
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini

  # install composer
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php

  # download dependencies via composer
  - php composer.phar install --no-interaction --no-progress

  # download phpunit
  - appveyor DownloadFile https://phar.phpunit.de/phpunit.phar

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php phpunit.phar
