services:
    Symplify\LatteToTwigConverter\:
        resource: ".."
        exclude: "../{Contract}"

    Symfony\Component\Console\Application: ~

    # SymfonyStyle
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Style\SymfonyStyle: ~
