services:
    # for 3rd party usage without autowire defaults compiler pass
    _defaults:
        autowire: true

    Symplify\BetterPhpDocParser\:
        resource: '../'
        exclude: '../{DependencyInjection,PhpDocParser/Ast/Type/*,*/*Info.php,*Info.php}'

    PHPStan\PhpDocParser\Lexer\Lexer: ~
    PHPStan\PhpDocParser\Parser\TypeParser: ~
    PHPStan\PhpDocParser\Parser\ConstExprParser: ~

    PHPStan\PhpDocParser\Parser\PhpDocParser:
        alias: 'Symplify\BetterPhpDocParser\PhpDocParser\PositionAwarePhpDocParser'
