parameters:
    migrator_sculpin:
        paths_to_remove:
            - 'sculpin.json'
            - 'sculpin.lock'
            - 'app/SculpinKernel.php'

        paths_to_move:
            # renames
            'app/config': 'source/_data'
            'source/_views': 'source/_layouts'

        apply_regular_in_paths:
            'source':
                # parameters are accessed directly, without any prefix - see https://regex101.com/r/PvaeHS/1

                # remove --- --- in the start
                '#^\-\-\-\n\-\-\-\n#m': ''

                # strip_html
                '#(.*|\*)strip_html(.*)#': '$1striphtml$2'

                # change include html suffix to twig
                '#({% include )(.*?).html( %})#': "$1'$2.twig'$3"

                # change "remove" to "replace" - @see https://regex101.com/r/iTaipb/2
                '#(\|(\s+)?)(?<filter>remove):\s*(?<value>.*?)\s*(\||}})#': "$1replace($4, '')$5"

                # replace "contains" with "in" - @see https://regex101.com/r/iTaipb/3
                '#({(%|{).*?)\s*(?<value>\w+)\s*contains\s*(?<needle>.*?)(\s)#': '$1 $4 in $3$5'

                # replace "assign" with "set"
                '#({%)\s*assign\s*(.*?)#': '$1 set $2'
                '#{% capture (.*?) endcapture %}#': '{% set $1 endset %}'

                '#^(use|generator): (.*?)$\s*#ms': ''
                '#^(permalink):(\s*(.*?)$\s*)#ms': 'outputPath:$2'
                '#(href="){{\s*(public_site|site\.url)\s*}}(\/)#m': '$1$3'

            source/_posts:
                # remove layout from posts, not needed
                '#^layout: \w+\s+#ms': ''
                '#^(date|date_gmt): (.*?)$\s*#m': ''

services:
    _defaults:
        public: true
        autowire: true

    Symplify\Statie\MigratorSculpin\:
        resource: '../src'
