services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symplify\Statie\:
        resource: '../src'
        exclude: '../src/{Exception,Renderable/File/File.php,Renderable/File/*File.php,Event}'

    # bin file
    Symplify\Statie\Console\Application: ~

    # rest api
    Symplify\PackageBuilder\Http\BetterGuzzleClient: ~
    GuzzleHttp\Client: ~

    ParsedownExtra:
        class: ParsedownExtra

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\Yaml\Parser: ~
    Symfony\Component\Filesystem\Filesystem: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
