name: Build Scoped Packages

on:
    push:
        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    build_scoped_packages:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                scoped_package:
                    -
                        directory: 'easy-coding-standard'
                        binary_file_name: 'ecs'

        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            # --prefer-lowest makes sure there are the same package in root + package
            -   run: composer update --no-progress --ansi

            # 1. install package dependencies
            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths packages/${{ matrix.scoped_package.directory }}/composer.json --ansi

            # --prefer-lowest makes sure there are the same package in root + package - that prevents see https://github.com/symplify/symplify/pull/2442/checks?check_run_id=1348085811#step:8:5
            -
                run: composer update --working-dir packages/${{ matrix.scoped_package.directory }} --ansi --no-dev

            # 2. scope it
            -   run: vendor/bin/php-scoper add-prefix packages/${{ matrix.scoped_package.directory }} --output-dir packages-scoped/${{ matrix.scoped_package.directory }} --config packages/${{ matrix.scoped_package.directory }}/scoper.inc.php --force --ansi
            -   run: composer dump-autoload --working-dir packages-scoped/${{ matrix.scoped_package.directory }} --ansi --optimize --classmap-authoritative
            -   run: packages/package-scoper/bin/package-scoper scope-composer-json packages-scoped/${{ matrix.scoped_package.directory }}/composer.json --ansi

            # 3. run it
            -   run: chmod 777 ./packages-scoped/${{ matrix.scoped_package.directory }}/bin/${{ matrix.scoped_package.binary_file_name }}

            # 4. get tag - see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            # 5. split it to remote repository
            # see https://github.com/cpina/github-action-push-to-another-repository
            -
                # Uses an action in the root directory
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages-scoped/${{ matrix.scoped_package.directory }}'
                    split-repository-organization: 'symplify'
                    split-repository-name: '${{ matrix.scoped_package.directory }}-prefixed'
                    tag: ${{ steps.previous_tag.outputs.tag }}
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
