# builds the content of https://github.com/symplify/easy-coding-standard

# inspiration from https://github.com/phpstan/phpstan-src/blob/master/.github/workflows/phar.yml
# and from https://github.com/rectorphp/rector/blob/main/.github/workflows/build_scoped_rector.yaml

name: Build ECS Prefixed

on:
    push:
        branches:
            - main

        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    build_ecs_prefixed:
        runs-on: ubuntu-latest
        steps:
            # make dev build run a bit to avoid collission with tagged build
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                run: sleep 120

            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   run: composer update --no-progress --ansi

            # 1. install package dependencies
            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths packages/easy-coding-standard/composer.json --ansi

            -
                run: composer install --working-dir packages/easy-coding-standard --ansi --no-dev

            # 2. prepare build directory
            -   run: cp -r packages/easy-coding-standard/. ecs-build
            # remove test files
            -   run: rm -rf ecs-build/tests ecs-build/packages/changed-files-detector/tests ecs-build/packages/configuration/tests ecs-build/packages/fixer-runner/tests ecs-build/packages/sniff-runner/tests ecs-build/packages/snippet-formatter/tests

            # 3. downgrade
            -   run: sh packages/easy-coding-standard/build/downgrade-ecs.sh ecs-build

            # 4. prefix
            -   run: sh packages/easy-coding-standard/build/build-ecs-scoped.sh ecs-build ecs-prefixed-downgraded

            -   run: chmod 777 ./ecs-prefixed-downgraded/bin/ecs

            # copy github actoins to repository, so tests run there too
            -   run: cp -R packages/easy-coding-standard/build/target-repository/. ecs-prefixed-downgraded

            # clone remote repository, so we can push it
            -
                uses: "actions/checkout@v2"
                with:
                    repository: symplify/easy-coding-standard
                    path: remote-repository
                    token: ${{ secrets.ACCESS_TOKEN }}

            # remove remote files, to avoid piling up dead code in remote repository
            -   run: rm -rf remote-repository/bin remote-repository/config remote-repository/src remote-repository/packages remote-repository/vendor

            # copy repository meta files
            -   run: cp -R ecs-prefixed-downgraded/. remote-repository

            # setup git
            -
                working-directory: remote-repository
                run: |
                    git config user.email "tomas.vot@gmail.com"
                    git config user.name "Tomas Votruba"

            # 7. commit metadata
            -
                name: "Get Git log"
                id: git-log
                run: echo ::set-output name=log::$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='%H %s' | sed -e 's/^/https:\/\/github.com\/symplify\/symplify\/commit\//')

            # 8.A publish it to remote repository without tag
            -
                name: "Commit Prefixed - main"
                working-directory: remote-repository
                if: "!startsWith(github.ref, 'refs/tags/')"
                run: |
                    git add --all
                    git commit -m "Updated ECS to commit ${{ github.event.after }}" -m "${{ steps.git-log.outputs.log }}"
                    git push --quiet origin main

            # 8.B publish it to remote repository with tag
            -
                name: "Commit Prefixed - tag"
                working-directory: remote-repository
                if: "startsWith(github.ref, 'refs/tags/')"
                run: |
                    git add --all
                    git commit -m "ECS ${GITHUB_REF#refs/tags/}" -m "${{ steps.git-log.outputs.log }}"
                    git push --quiet origin main
                    git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
                    git push --quiet origin ${GITHUB_REF#refs/tags/}
