# builds the content of https://github.com/symplify/easy-coding-standard-prefixed
# inspiration from https://github.com/phpstan/phpstan-src/blob/master/.github/workflows/phar.yml
name: Build ECS Prefixed

on:
    push:
        branches:
            - main

        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    build_ecs_prefixed:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            # --prefer-lowest makes sure there are the same package in root + package
            -   run: composer update --no-progress --ansi

            # 1. install package dependencies
            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths packages/easy-coding-standard/composer.json --ansi

            # --prefer-lowest makes sure there are the same package in root + package - that prevents see https://github.com/symplify/symplify/pull/2442/checks?check_run_id=1348085811#step:8:5
            -
                run: composer update --working-dir packages/easy-coding-standard --ansi --no-dev

            # 2. scope it
            -   run: vendor/bin/php-scoper add-prefix packages/easy-coding-standard --output-dir packages-scoped/easy-coding-standard --config packages/easy-coding-standard/scoper.inc.php --force --ansi
            -   run: composer dump-autoload --working-dir packages-scoped/easy-coding-standard --ansi --optimize --classmap-authoritative
            -   run: packages/package-scoper/bin/package-scoper scope-composer-json packages-scoped/easy-coding-standard/composer.json --ansi

            # 3. run it
            -   run: chmod 777 ./packages-scoped/easy-coding-standard/bin/ecs

            # 4. copy github actoins to repository, so tests run there too
            -   run: cp -R build/ecs-scoped/target-repository/. packages-scoped/easy-coding-standard

            # 5. copy repository meta files
            -   run: cp -R packages-scoped/easy-coding-standard/. easy-coding-standard-prefixed

            # 6. clone remote repository, so we can push it
            -
                uses: "actions/checkout@v2"
                with:
                    repository: symplify/easy-coding-standard-prefixed
                    path: remote-repository
                    token: ${{ secrets.ACCESS_TOKEN }}

            # 5. setup git
            -
                working-directory: remote-repository
                run: |
                    git config user.email "tomas.vot@gmail.com"
                    git config user.name "Tomas Votruba"

            # commit metadata
            -
                name: "Get Git log"
                id: git-log
                run: echo ::set-output name=log::$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='%H %s' | sed -e 's/^/https:\/\/github.com\/symplify\/symplify\/commit\//')

            # 8.A publish it to remote repository without tag
            -
                name: "Commit Prefixed - main"
                working-directory: remote-repository
                if: "!startsWith(github.ref, 'refs/tags/')"
                run: |
                    git add --all
                    git commit -m "Updated ECS to commit ${{ github.event.after }}" -m "${{ steps.git-log.outputs.log }}"
                    git push --quiet origin main
            # 8.B publish it to remote repository with tag
            -
                name: "Commit Prefixed - tag"
                working-directory: remote-repository
                if: "startsWith(github.ref, 'refs/tags/')"
                run: |
                    git add --all
                    git commit -m "ECS ${GITHUB_REF#refs/tags/}" -m "${{ steps.git-log.outputs.log }}"
                    git push --quiet origin main
                    git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
                    git push --quiet origin ${GITHUB_REF#refs/tags/}
