name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: PHPStan
                        run: composer phpstan

                    -
                        name: Check for Git Conflicts
                        run: packages/easy-ci/bin/easy-ci check-conflicts .

                    -
                        name: Check File Length
                        run: packages/easy-ci/bin/easy-ci validate-file-length packages

                    -
                        name: Composer Validate
                        run: composer validate

                    -
                        name: Commented Code
                        run: packages/easy-ci/bin/easy-ci check-commented-code packages --line-limit 5 --ansi

                    -
                        name: Binary File Run
                        run: |
                            # test run bin files
                            packages/easy-coding-standard/bin/ecs -h --ansi
                            packages/monorepo-builder/bin/monorepo-builder --ansi
                            packages/rule-doc-generator/bin/rule-doc-generator --ansi
                            packages/config-transformer/bin/config-transformer --ansi
                            packages/easy-ci/bin/easy-ci --ansi
                            packages/easy-testing/bin/easy-testing --ansi
                            packages/vendor-patches/bin/vendor-patches --ansi
                            packages/phpunit-upgrader/bin/phpunit-upgrader --ansi
                            packages/psr4-switcher/bin/psr4-switcher --ansi

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
