name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - master

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: PHPStan
                        run: composer phpstan

                    -
                        name: Check for Git Conflicts
                        run: packages/easy-ci/bin/easy-ci check-conflicts .

                    -
                        name: Composer Validate
                        run: composer validate --strict

                    -
                        name: Binary File Run
                        run: |
                            # test run bin files
                            packages/easy-coding-standard/bin/ecs --ansi
                            packages/changelog-linker/bin/changelog-linker --ansi
                            packages/monorepo-builder/bin/monorepo-builder --ansi
                            packages/easy-coding-standard/bin/ecs --ansi
                            # packages/rule-doc-generator/bin/rule-doc-generator --ansi

                            # test "check" options
                            packages/easy-coding-standard/bin/ecs check packages/changelog-linker/src --no-progress-bar --no-error-table --clear-cache --ansi

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--ignore-platform-req php"

            -   run: ${{ matrix.actions.run }}
