name: Daily Pull Requests

on:
    schedule:
        # https://crontab.guru/once-a-day
        -   cron: "0 0 * * *"

jobs:
    daily_pull_requests:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Re-Generate Docs"
                        run: "composer docs"
                        branch: 'automated-re-generate-docs'

                    -
                        name: "Re-Apply Coding Standards"
                        run: "composer fix-cs"
                        branch: 'automated-re-apply-coding-standards'

                    -
                        name: "Re-Propagate Composer Dependencies to Packages"
                        run: "composer propagate"
                        branch: 'automated-re-propagate-dependencies'

                    -
                        name: "Re-Apply Rector Rules"
                        run: |
                            vendor/bin/rector rectify --config rector-ci.php --ansi --no-progress-bar
                            packages/easy-coding-standard/bin/ecs check --match-git-diff --fix --ansi
                        branch: 'automated-re-apply-rector'

        name: ${{ matrix.actions.name }}

        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    commit-message: "[automated] ${{ matrix.actions.name }}"
                    base: 'master'
                    branch: ${{ matrix.actions.branch }}
                    title: '[automated] ${{ matrix.actions.name }}'
                    delete-branch: true
