name: Master Only

on:
    push:
        branches:
            - master

jobs:
    master_only:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Twitter API Tests'
                        run: vendor/bin/phpunit --group api

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # needed for tests
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi

            -
                name: ${{ matrix.actions.name }}
                run: ${{ matrix.actions.run }}
