# inspired at https://github.com/rectorphp/rector/blob/master/.github/workflows/rector_ci.yaml

name: Rector

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            # get package json list
            -
                id: output_data
                run: echo "::set-output name=matrix::$(packages/monorepo-builder/bin/monorepo-builder packages-json)"

        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    rector:
        # run only for repository write-users
        runs-on: ubuntu-latest
        needs: provide_packages_json

        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.provide_packages_json.outputs.matrix )}}

        steps:
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v2
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            # in forks, the token is not available - so we cannot us eit
            -
                 if: github.event.pull_request.head.repo.full_name != github.repository
                 uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/rector process packages/${{ matrix.package }} --ansi

            -   run: packages/easy-coding-standard/bin/ecs check --match-git-diff --fix --ansi

            # see https://github.com/EndBug/add-and-commit
            -
                # commit only to core contributors who have repository access
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: EndBug/add-and-commit@v5.1.0
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: .
                    message: "[ci-review] Rector Rectify"
                    author_name: "Tomas Votruba"
                    author_email: "tomas.vot@gmail.com"
                env:
                    # to get push access
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
