name: Split Unused Packages

on:
    # no need to run always, just once a day is enough
    schedule:
        # https://crontab.guru/#0_0_*_*_* - every day at midnight
        -   cron: '0 0 * * *'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    unused_packages:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    # PHP 7.3 is required by "icanhazstring/composer-unused"
                    php-version: 7.3
                    coverage: none

            # see https://github.com/composer-unused/composer-unused
            -
                name: Unused Packages
                run: composer require icanhazstring/composer-unused --dev

            -   run: composer unused

    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            # get package json list
            -
                id: set-matrix
                run: echo "::set-output name=matrix::$(packages/monorepo-builder/bin/monorepo-builder packages-json)"

        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    split_unused_packages:
        needs: provide_packages_json

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths ${{ matrix.package_path }}/composer.json --ansi

            -   run: composer update --no-progress --ansi --working-dir ${{ matrix.package_path }}

            -   run: composer require icanhazstring/composer-unused --dev --ansi --working-dir ${{ matrix.package_path }}

            -
                name: Unused Packages of ${{ matrix.package_path }}
                working-directory: ${{ matrix.package_path }}
                run: composer unused --ansi
